apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: fydyn6bjl-nodejs
  janus-idp.io/tekton: fydyn6bjl-nodejs
  backstage.io/kubernetes-id: fydyn6bjl-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fydyn6bjl-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
