apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: fydyn6bjl-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fydyn6bjl-nodejs 
  name: fydyn6bjl-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: fydyn6bjl-nodejs 
